apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forkwise-app
resources:
  - namespace.yaml
  - integration-configmap.yaml
  - pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - mealie-deployment.yaml
  - mealie-service.yaml
