apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: forkwise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      nodeSelector:
        forkwise.io/entrypoint: "true"
      containers:
        - name: mealie
          image: ghcr.io/itsnotaka/mealie:ml-ui-amd64
          ports:
            - containerPort: 9000
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: UTC
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: mealie-credentials
                  key: base-url
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-credentials
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-credentials
                  key: postgres-password
            - name: POSTGRES_SERVER
              value: mealie-postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mealie-credentials
                  key: postgres-db
            - name: SUBSTITUTION_API_URL
              valueFrom:
                configMapKeyRef:
                  name: forkwise-integration
                  key: SUBSTITUTION_API_URL
            - name: SUBSTITUTION_FEEDBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: forkwise-integration
                  key: SUBSTITUTION_FEEDBACK_URL
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
