apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-postgres-pvc
  namespace: forkwise-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-pvc
  namespace: forkwise-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
