apiVersion: v1
kind: ServiceAccount
metadata:
  name: subst-cronjob-sa
  namespace: canary-proj01
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-reader
  namespace: canary-proj01
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: subst-cronjob-sa-deployment-reader
  namespace: canary-proj01
subjects:
  - kind: ServiceAccount
    name: subst-cronjob-sa
    namespace: canary-proj01
roleRef:
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io
