apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canary-proj01
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - check-promote-rbac.yaml
  - check-promote-cronjob.yaml
