apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subst-serving
  namespace: production-proj01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subst-serving
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
