apiVersion: v1
kind: ConfigMap
metadata:
  name: forkwise-data-config
  namespace: forkwise-data
data:
  OS_ENDPOINT: https://chi.tacc.chameleoncloud.org:7480
  BUCKET: data-proj01
  MODEL_PREFIX: models
  VAL_DATASET_KEY: data/raw/recipe1msubs/val.json
  SERVING_URL: http://subst-serving.production-proj01.svc.cluster.local:8000/predict
  CANARY_SERVING_URL: http://subst-serving.canary-proj01.svc.cluster.local:8000/predict
  CANARY_TRAFFIC_PERCENT: "0.10"
  REQUESTS_PER_SEC: "1"
  MIN_NEW_SAMPLES: "50"
  OOV_THRESHOLD: "0.15"
  LOW_CONFIDENCE_THRESHOLD: "0.5"
  MIN_REQUESTS_EXPECTED: "10"
