apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forkwise-data
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-feedback.yaml
  - service-feedback.yaml
  - deployment-generator.yaml
  - cronjob-batch.yaml
  - cronjob-drift.yaml
  - cronjob-training.yaml
